server:
  port: ${GATEWAY_SERVER_PORT:9292}

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: game-service
          uri: http://localhost:7331/
          predicates:
            - Path=/games/squadlocke/**