server:
  port: ${GATEWAY_SERVER_PORT:9292}

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: account-service-protected
          uri: ${ACCOUNT_SERVICE_HOST}:${ACCOUNT_SERVICE_PORT:6091}
          predicates:
            - Path=/users/me, /auth/**
          filters:
            - AuthFilter
        - id: account-service-open
          uri: ${ACCOUNT_SERVICE_HOST}:${ACCOUNT_SERVICE_PORT:6091}
          predicates:
            - Path=/oauth2/authorization/discord, /login/oauth2/code/discord, /users/**
        - id: game-service
          uri: ${GAME_SERVICE_HOST}:${GAME_SERVICE_PORT:7331}
          predicates:
            - Path=/games/squadlocke/**, /generations/**, /encounters/**
          filters:
            - AuthFilter

application:
  gateway-settings:
    allowedOrigin: "http://${CORS_ALLOWED_HOST}:${CORS_ALLOWED_PORT}"
  filter:
    auth:
      uri: ${AUTH_FILTER_URI}