server:
  port: ${GATEWAY_SERVER_PORT:9292}

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: account-service-open
          uri: http://localhost:6091/
          predicates:
            - Path=/login, /oauth2/authorization/discord
        - id: account-service-protected
          uri: http://localhost:6091/
          predicates:
            - Path=/users/**, /auth/**
          filters:
            - AuthFilter
        - id: game-service
          uri: ${GAME_SERVICE_HOST}:${GAME_SERVICE_PORT:7331}
          predicates:
            - Path=/games/squadlocke/**
          filters:
            - AuthFilter